project:
  type: website
  output-dir: docs

website:
  title: "Afrooz Razi"
  navbar:
    background: dark
    foreground: light
    search: true
    right:
      - text: "About"
        file: about.qmd
      - text: "Example analysis"
        file: example_analysis.qmd
      - icon: github
        href: https://github.com/raziafrooz
      - icon: twitter
        href: https://twitter.com/raziafro0z


format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

